# Permalinks
permalink:        pretty

# Setup
title:            Sameer Manek
tagline:          ''
#url:              http://sameermanek.github.io
url:              http://sameermanek.com
paginate:         5
#baseurl:          /
author:
  name:           Sameer Manek
  url:            http://sameermanek.github.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
    Photos: 'https://www.flickr.com/photos/sameermanek/'
    Projects: '/projects/'
    Archive: '/archive/'
    About: '/about/'
